application: heartsnet2013
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public_html/index.html
  upload: public_html/index.html

- url: /
  static_dir: public_html